apiVersion: v1
kind: ConfigMap
metadata:
  name: bcc-cvote-config
  namespace: voting-prod
data:
  FLASK_ENV: "production"
  GUNICORN_WORKERS: "2"
  LOG_LEVEL: "info"
  FRONTEND_URL: "https://bcc-cvote.yourdomain.com"
